server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
  shutdown: graceful

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true


common:
  html-regex: <(/)?([a-zA-Z]*)(\\s[a-zA-Z]*=[^>]*)?(\\s)*(/)?>
openapi:
  kakao:
    url: https://dapi.kakao.com/v2/local/search/keyword.json
    #    api-key: KakaoAK 332bb307e35d65b793cdeac9e3de85a7
    api-key: ENC(tREsoGFN9qGQHCGofeS4orD2wOwPpoZFM0o0dAz83y7miOx2zgteOxQEdTzXD+xlJdK0XSKbLd0=)
    place:
      objects: documents
      name: place_name
      address: address_name
      address-road: road_address_name
    search-count: 5
  naver:
    url: https://openapi.naver.com/v1/search/local.json
    #    client-id: gWm0ElB1RX6DAjcxGfQ8
    client-id: ENC(bL/9J1zOOUTH9f0gduj1eWa9gPApyCqu1Af3YJppkZc=)
    #    client-secret: v5sxoZKdW6
    client-secret: ENC(FDAXIZZQhtmtE6CxYy0GqHYTMVIecQ4E)
    place:
      objects: items
      name: title
      address: address
      address-road: roadAddress
    search-count: 5

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
